function success = wtImportFromSelectGUI(importToEEGLabData) 
    success = false;
    wtLog = WTLog();
    
    WTUtils.mustBeA(importToEEGLabData, ?WTImportToEEGLabCfg)

    answer = { importToEEGLabData.EEPFlag, ...
        importToEEGLabData.EGIFlag, ...
        importToEEGLabData.BRVFlag, ...
        importToEEGLabData.EEGLabFlag }; 

    cb_radiobutton1 = [ ...
        'get(gcbf, ''userdata'');' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton1''), ''Value'', 1);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton2''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton3''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton4''), ''Value'', 0);' ];

    cb_radiobutton2 = [ ...
        'get(gcbf, ''userdata'');' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton1''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton2''), ''Value'', 1);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton3''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton4''), ''Value'', 0);' ];

    cb_radiobutton3 = [ ...
        'get(gcbf, ''userdata'');' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton1''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton2''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton3''), ''Value'', 1);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton4''), ''Value'', 0);' ];

    cb_radiobutton4 = [ ...
        'get(gcbf, ''userdata'');' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton1''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton2''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton3''), ''Value'', 0);' ...
        'set(findobj(gcbf, ''tag'', ''radiobutton4''), ''Value'', 1);' ];

    parameters = { ...
        { 'style' 'text'        'string' 'Import segmented files from the following system:' } ...
        { 'style' 'text'        'string' '' } ...
        { 'style' 'radiobutton' 'tag'    'radiobutton1' 'string' 'EEP'    'value'  answer{1,1} 'callback' cb_radiobutton1 } ...
        { 'style' 'radiobutton' 'tag'    'radiobutton2' 'string' 'EGI'    'value'  answer{1,2} 'callback' cb_radiobutton2 } ...
        { 'style' 'radiobutton' 'tag'    'radiobutton3' 'string' 'BRV'    'value'  answer{1,3} 'callback' cb_radiobutton3 } ...
        { 'style' 'radiobutton' 'tag'    'radiobutton4' 'string' 'EEGLAB' 'value'  answer{1,4} 'callback' cb_radiobutton4 } };

    geometry = { 1 1 1 1 1 1 };

    while true
        [answer, ~, strhalt] = WTUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters,'title', 'Import segmented EEG');

        if ~strcmp(strhalt,'retuninginputui')
            wtLog.dbg('User quitted import configuration dialog');
            return;
        end

        % This is a double check, if for any reason the configuration file was changed manually
        if sum(cellfun(@(e) e, answer)) ~= 0
            break
        end
        WTUtils.eeglabMsgDlg('Warning', 'You must select one EEG system among EEP, EGI, BRV, EEGLAB')
    end

    importToEEGLabData.EEPFlag = answer{1,1};
    importToEEGLabData.EGIFlag = answer{1,2};
    importToEEGLabData.BRVFlag = answer{1,3};
    importToEEGLabData.EEGLabFlag = answer{1,4};
    success = true;
end