% Copyright (C) 2024 Eugenio Parise, Luca Filippin
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <https://www.gnu.org/licenses/>.

classdef WTAppConfigGUI

    methods(Static)
        function wtAppConfig = configureApplication(updateCurrent, persist, warnReload)
            updateCurrent = nargin > 0 && updateCurrent;
            persist = nargin > 1 && persist;
            warnReload =  nargin > 2 && warnReload;
            wtLog = WTLog();
            wtAppConfig = [];

            if updateCurrent
                wtAppConfigCrnt = WTAppConfig();
            else
                [wtAppConfigCrnt, success] = WTAppConfig(false).load(false);
                if ~success
                    WTDialogUtils.errDlg('Application configuration', 'Failed load the application configuration!');
                    return
                end
            end

            wtAppConfig = copy(wtAppConfigCrnt);
            
            cbPrjLog = [ ...
                'status = ''off'';' ...
                'if get(findobj(gcbf, ''tag'', ''kPrjLog''), ''value''),' ... 
                '  status = ''on'';' ...
                'end;' ...
                'set(findobj(gcbf, ''-regexp'', ''tag'', ''prjLog.*''), ''enable'', status);' ];
            cbMuteStdLog = [ ...
                'status = ''on'';' ...
                'if get(findobj(gcbf, ''tag'', ''kStdLogMute''), ''value''),' ... 
                '  status = ''off'';' ...
                'end;' ...
                'set(findobj(gcbf, ''-regexp'', ''tag'', ''stdLog.*''), ''enable'', status);' ];

            logLvlStrs = WTLog.LevelStrs;   
            colorMaps = WTGraphicUtils.getColorMaps();
            selectedColorMapIdx = find(strcmp(colorMaps, wtAppConfig.PlotsColorMap));
            selectedColorMapIdx = WTCodingUtils.ifThenElse(isempty(selectedColorMapIdx), 1, selectedColorMapIdx);

            answer = { ...
                wtAppConfig.ShowSplashScreen ...
                wtAppConfig.DangerWarnings ...
                selectedColorMapIdx ...
                wtAppConfig.ProjectLog ...
                wtAppConfig.ProjectLogLevel ...
                wtAppConfig.MuteStdLog ...
                wtAppConfig.ColorizedLog ...
                wtAppConfig.DefaultStdLogLevel ...
            };

            function parameters = setParameters(answer)
                enablePrjLogOpt = WTCodingUtils.ifThenElse(wtAppConfig.ProjectLog, 'on', 'off');
                enableStdLogOpt = WTCodingUtils.ifThenElse(wtAppConfig.MuteStdLog, 'off', 'on');

                parameters = { ...
                    { 'style' 'text'      'string' 'Show splash screen' } ...
                    { 'style' 'checkbox'  'value'  answer{1,1} } ...
                    { 'style' 'text'      'string' 'Warn about possibly dangerous operations' } ...
                    { 'style' 'checkbox'  'value'  answer{1,2} } ...
                    { 'style' 'text'      'string' 'Plots color map' } ...
                    { 'style' 'popupmenu' 'string' colorMaps 'value' answer{1,3} }...
                    { 'style' 'text'      'string' 'Project log' } ...
                    { 'style' 'checkbox'  'value'  answer{1,4} 'tag' 'kPrjLog' 'callback' cbPrjLog } ...
                    { 'style' 'text'      'string' 'Project log level' 'tag' 'prjLogLvlTxt' 'enable' enablePrjLogOpt } ...
                    { 'style' 'popupmenu' 'string' logLvlStrs 'value' answer{1,5} 'tag' 'prjLogLvl' 'enable' enablePrjLogOpt }...
                    { 'style' 'text'      'string' 'Mute standard log'  } ...
                    { 'style' 'checkbox'  'value'  answer{1,6} 'tag' 'kStdLogMute' 'callback' cbMuteStdLog } ...
                    { 'style' 'text'      'string' 'Colorised standard log' 'tag' 'stdLogColorTxt' } ...
                    { 'style' 'checkbox'  'value'  answer{1,7} 'tag' 'stdLogColor' 'enable' enableStdLogOpt } ...
                    { 'style' 'text'      'string' 'Default standard log level' 'tag' 'stdLogLvlTxt' 'enable' enableStdLogOpt } ...
                    { 'style' 'popupmenu' 'string' logLvlStrs 'value' answer{1,8} 'tag' 'stdLogLvl' 'enable' enableStdLogOpt } ...
                };
            end
            
            geometry = { [0.6 0.4] [0.6 0.4] [0.6 0.4] [0.6 0.4] [0.6 0.4] [0.6 0.4] [0.6 0.4] [0.6 0.4] };
            success = false;
            anyChange = false;

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Configuration');
                
                if isempty(answer)
                    wtAppConfig = [];
                    return 
                end

                success = all([ ...
                    WTTryExec(@()set(wtAppConfig, 'PlotsColorMap', colorMaps{answer{1,3}})).logWrn().displayWrn('Review parameter', 'Invalid PlotsColorMap').run().Succeeded ...
                    WTTryExec(@()set(wtAppConfig, 'ShowSplashScreen', answer{1,1})).logWrn().displayWrn('Review parameter', 'Invalid ShowSplashScreen').run().Succeeded ... 
                    WTTryExec(@()set(wtAppConfig, 'DangerWarnings', answer{1,2})).logWrn().displayWrn('Review parameter', 'Invalid DangerWarnings').run().Succeeded ... 
                    WTTryExec(@()set(wtAppConfig, 'ProjectLog', answer{1,4})).logWrn().displayWrn('Review parameter', 'Invalid ProjectLog').run().Succeeded ... 
                    WTTryExec(@()set(wtAppConfig, 'ProjectLogLevel', answer{1,5})).logWrn().displayWrn('Review parameter', 'Invalid ProjectLogLevel').run().Succeeded ... 
                    WTTryExec(@()set(wtAppConfig, 'MuteStdLog', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid MuteStdLog').run().Succeeded ... 
                    WTTryExec(@()set(wtAppConfig, 'ColorizedLog', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid ColorizedLog').run().Succeeded ... 
                    WTTryExec(@()set(wtAppConfig, 'DefaultStdLogLevel', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid DefaultStdLogLevel').run().Succeeded ... 
                ]);

                if ~success
                    continue
                end

                anyChange = ~wtAppConfigCrnt.equalTo(wtAppConfig);

                if ~wtAppConfigCrnt.MuteStdLog && wtAppConfig.MuteStdLog && ...
                       ~WTEEGLabUtils.eeglabYesNoDlg('Confirm application configuration', ...
                            'Muting standard log might hide important information! Continue?')
                    success = false;
                    anyChange = false;
                elseif wtAppConfigCrnt.DangerWarnings && ~wtAppConfig.DangerWarnings && ...
                       ~WTEEGLabUtils.eeglabYesNoDlg('Confirm application configuration', ...
                        'Disabling warnings on possibly dangerous operations is generally not a good idea! Continue?')
                    success = false;
                    anyChange = false;
                end
            end

            if ~anyChange
                return
            end

            if updateCurrent
                wtAppConfig.copyTo(WTAppConfig());
            end

            if persist && ~wtAppConfig.persist()
                WTDialogUtils.errDlg('Application configuration', 'Failed to save the application configuration!');
                wtAppConfig = [];
            elseif warnReload && WTSession().IsOpen
                WTDialogUtils.wrnDlg('Application configuration', 'Quit and open again wtools to load the updated configuration');
            end
        end
    end
end