% Copyright (C) 2024 Eugenio Parise, Luca Filippin
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <https://www.gnu.org/licenses/>.

classdef WTBaselineChopGUI
    
    methods(Static)
        function success = defineBaselineChopParams(baselineChopParams, lockEvok, lockPower)
            success = false;
            WTValidations.mustBe(baselineChopParams, ?WTBaselineChopCfg);
            wtLog = WTLog();            

            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');

            enableBC = WTCodingUtils.ifThenElse(...
                baselineChopParams.BaselineSubtraction || ...
                baselineChopParams.BaselineNormalization, 'on', 'off');

            answer = { ...
                num2str(baselineChopParams.ChopTimeMin), ...
                num2str(baselineChopParams.ChopTimeMax), ...
                num2str(baselineChopParams.BaselineTimeMin), ...
                num2str(baselineChopParams.BaselineTimeMax), ...
                baselineChopParams.EvokedOscillations, ... 
                baselineChopParams.TransformPower, ... 
                baselineChopParams.BaselineSubtraction, ...
                baselineChopParams.BaselineNormalization};
            
            cbEnableBC = [ 
                'bc = get(findobj(gcbf, ''tag'', ''BC''), ''value'');' ... 
                'bn = get(findobj(gcbf, ''tag'', ''BN''), ''value'');' ...
                'set(findobj(gcbf, ''tag'', ''BRNG''), ''enable'', WTCodingUtils.ifThenElse(bc || bn, ''on'', ''off''));' ...
            ];

            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'     'string' 'NOTE: The baseline is calculated before signal chopping. Both baseline and' } ...
                    { 'style' 'text'     'string' 'chopping ranges refer to the same initial time domain.' } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'text'     'string' 'Chop Ends (ms):              Left' } ...
                    { 'style' 'edit'     'string'  answer{1,1} } ...
                    { 'style' 'text'     'string' 'Right' } ...
                    { 'style' 'edit'     'string'  answer{1,2} } ...
                    { 'style' 'text'     'string' 'Baseline Range (ms):    From' } ...
                    { 'style' 'edit'     'string'  answer{1,3} 'tag' 'BRNG' 'enable' enableBC } ...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string'  answer{1,4} 'tag' 'BRNG' 'enable' enableBC } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'value'  answer{1,5} 'string' 'Evoked Oscillations' 'enable'  enableEvok } ...
                    { 'style' 'checkbox' 'value'  answer{1,6} 'string' 'Transform Power' 'enable'  enablePower } ...
                    { 'style' 'checkbox' 'value'  answer{1,7} 'string' 'Baseline Subtraction' 'tag' 'BC' 'callback', cbEnableBC } ...
                    { 'style' 'checkbox' 'value'  answer{1,8} 'string' 'Baseline Normalization' 'tag' 'BN' 'callback' cbEnableBC} };
            end

            geometry = { 1 1 1 [1 0.5 0.5 0.5] [1 0.5 0.5 0.5] 1 [0.5 0.5] [0.5 0.5] };

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Set baseline and edges chopping parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted baseline and chopping configuration dialog');
                    return % quit on cancel button
                end

                success = all([ ...
                    WTTryExec(@()set(baselineChopParams, 'ChopTimeMin', WTNumUtils.str2double(answer{1,1}))).logWrn().displayWrn('Review parameter', 'Invalid ChopTimeMin').run().Succeeded ...
                    WTTryExec(@()set(baselineChopParams, 'ChopTimeMax', WTNumUtils.str2double(answer{1,2}))).logWrn().displayWrn('Review parameter', 'Invalid ChopTimeMax').run().Succeeded ... 
                    WTTryExec(@()set(baselineChopParams, 'EvokedOscillations', answer{1,5})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ...
                    WTTryExec(@()set(baselineChopParams, 'TransformPower', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(baselineChopParams, 'BaselineSubtraction', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ... 
                    WTTryExec(@()set(baselineChopParams, 'BaselineNormalization', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded ...
                ]);

                if success
                    if ~baselineChopParams.BaselineSubtraction && ~baselineChopParams.BaselineNormalization
                        % Update baseline window only if baseline correction was selected, 
                        % otherwise retains previous values for convenience.
                        answer{1,3} = [];
                        answer{1,4} = [];
                    else
                        success = all([ ...
                            WTTryExec(@()set(baselineChopParams, 'BaselineTimeMin', WTNumUtils.str2double(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid BaselineTimeMin').run().Succeeded ...
                            WTTryExec(@()set(baselineChopParams, 'BaselineTimeMax', WTNumUtils.str2double(answer{1,4}))).logWrn().displayWrn('Review parameter', 'Invalid BaselineTimeMax').run().Succeeded ... 
                        ]);
                    end
                end

                success = success && WTTryExec(@()baselineChopParams.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 
            end
        end
    end
end