% Copyright (C) 2024 Eugenio Parise, Luca Filippin
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <https://www.gnu.org/licenses/>.

classdef WTPlotsGUI

    properties(Constant, Access = private)
        setScaleLabelCb = [
            'set(findobj(gcbf, ''tag'', ''LB''), ''string'',' ...
                'WTPlotUtils.getPlotConfigLabel(' ...
                    'get(findobj(gcbf, ''tag'', ''EO''), ''value''),' ...
                    'get(findobj(gcbf, ''tag'', ''PW''), ''value''),' ...
                    'get(findobj(gcbf, ''tag'', ''BC''), ''value''),' ...
                    'get(findobj(gcbf, ''tag'', ''BN''), ''value''),' ... 
                    'get(findobj(gcbf, ''tag'', ''DB''), ''value'')));' ...
        ];

        setScaleRangeCb = [
            'set(findobj(gcbf, ''tag'', ''RG''), ''string'',' ...
                'sprintf(WTConfigFormatter.FmtArray,' ... 
                'num2str(WTPlotUtils.getSuggestedScaleRange(' ...
                    'get(findobj(gcbf, ''tag'', ''PW''), ''value''),' ...
                    'get(findobj(gcbf, ''tag'', ''BC''), ''value''),' ...
                    'get(findobj(gcbf, ''tag'', ''BN''), ''value''),' ... 
                    'get(findobj(gcbf, ''tag'', ''DB''), ''value'')))));' ...
        ];
    end

    methods(Static)
        % subject = [] when the grand average directory is selected instead of a specific subject dir
        function [fileNames, filesPath, fileType, subject] = selectFilesToPlot(evokedOscillations, perSubject, averageOnly, maxFilesNum)
            wtProject = WTProject();
            wtLog = WTLog();
            ioProc = wtProject.Config.IOProc;
            subject = [];
            
            [fileType, fileExt] = ioProc.getGrandAverageFileTypeAndExtension(perSubject, evokedOscillations);
            fileFilter = {  sprintf('*_%s%s', fileType, fileExt), 'All Files' };

            while true
                title = 'Select files to plot';
                if maxFilesNum > 0
                    title = sprintf('%s\n[ Max %d files ]', title, maxFilesNum);
                end

                rootSelectionDir = WTCodingUtils.ifThenElse(averageOnly, ioProc.GrandAvgDir, ioProc.AnalysisDir);
                
                [fileNames, filesPath, ~] = WTDialogUtils.uiGetFiles(fileFilter, -1, maxFilesNum, title, ...
                    'MultiSelect', 'on', 'restrictToDirs', ['^' regexptranslate('escape', rootSelectionDir)], rootSelectionDir);
                if isempty(fileNames) 
                    wtLog.warn('No files to plot selected');
                    return
                end

                if averageOnly
                    break
                end
                
                subject = ioProc.getSubjectFromPath(filesPath);
                if ~isempty(subject) || ioProc.isGrandAvgDir(filesPath)
                    break
                end
                
                WTEEGLabUtils.eeglabMsgDlg('Warning', ...
                    'Directory:\n   ''%s''\ndoesn''t look like a subject directory.\nPlease select again...', filesPath)
            end
        end

        function success = defineAvgPlotsSettings(plotsPrms, lockEvok, lockPower, lockBaselineCorrect, lockBaselineNorm) 
            success = false;
            WTValidations.mustBe(plotsPrms, ?WTAvgPlotsCfg);
            wtLog = WTLog();
            
            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');
            enableBC = WTCodingUtils.ifThenElse(lockBaselineCorrect, 'off', 'on');
            enableBN = WTCodingUtils.ifThenElse(lockBaselineNorm, 'off', 'on');

            scaleLabel = WTPlotUtils.getPlotConfigLabel( ...
                plotsPrms.EvokedOscillations, ...
                plotsPrms.TransformPower, ...
                plotsPrms.BaselineSubtraction, ...
                plotsPrms.BaselineNormalization, ... 
                plotsPrms.Decibel);
            
            if isempty(plotsPrms.Scale)
                plotsPrms.Scale = WTPlotUtils.getSuggestedScaleRange( ...
                    plotsPrms.TransformPower, ...
                    plotsPrms.BaselineSubtraction, ...
                    plotsPrms.BaselineNormalization, ... 
                    plotsPrms.Decibel);
            end

            updateScaleCb = [ WTPlotsGUI.setScaleLabelCb WTPlotsGUI.setScaleRangeCb ];

            answer = { ...
                num2str(plotsPrms.TimeMin) ...
                num2str(plotsPrms.TimeMax) ...
                num2str(plotsPrms.FreqMin) ...
                num2str(plotsPrms.FreqMax) ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Scale)) ...
                plotsPrms.Contours ...
                plotsPrms.AllChannels ... 
                plotsPrms.Decibel ...
                plotsPrms.EvokedOscillations, ...
                plotsPrms.TransformPower ...
                plotsPrms.BaselineSubtraction ...
                plotsPrms.BaselineNormalization ...
            };

            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'     'string' 'Time (ms): From     ' } ...
                    { 'style' 'edit'     'string' answer{1,1} } ...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,2} }...
                    { 'style' 'text'     'string' 'Frequency (Hz): From' } ...
                    { 'style' 'edit'     'string' answer{1,3} }...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,4} } ...
                    { 'style' 'text'     'string' scaleLabel  'tag' 'LB' } ...
                    { 'style' 'edit'     'string' answer{1,5} 'tag' 'RG' } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Draw contours' 'value'  answer{1,6} } ...
                    { 'style' 'checkbox' 'string' 'Plot all channels' 'value'  answer{1,7} } ...
                    { 'style' 'checkbox' 'string' 'Decibel' 'value'  answer{1,8} 'tag' 'DB' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Evoked Oscillations' 'value'  answer{1,9} 'enable' enableEvok  'tag' 'EO' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Transform Power' 'value'  answer{1,10} 'enable' enablePower 'tag' 'PW' 'callback' updateScaleCb } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Baseline Subtraction' 'value' answer{1,11} 'enable' enableBC 'tag' 'BC' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Baseline Normalization' 'value' answer{1,12} 'enable' enableBN 'tag' 'BN' 'callback' updateScaleCb } ...
                    { 'style' 'text'     'string' '' } ...
                };
            end

            geometry = { 
                [0.25 0.15 0.15 0.15] ...
                [0.25 0.15 0.15 0.15] ...
                [0.25 0.45] ...
                1 ...
                [0.25 0.25 0.25] ...
                [0.25 0.25 0.25] ...
                [0.25 0.25 0.25] ...
            };
            
            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Set plots parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted average plots configuration dialog');
                    return 
                end
                
                success = all([ ...
                    WTTryExec(@()set(plotsPrms, 'TimeMin', WTNumUtils.str2double(answer{1,1}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMin').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TimeMax', WTNumUtils.str2double(answer{1,2}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMax').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMin', WTNumUtils.str2double(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMin').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMax', WTNumUtils.str2double(answer{1,4}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMax').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Scale', WTNumUtils.str2nums(answer{1,5}))).logWrn().displayWrn('Review parameter', 'Invalid Scale').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Contours', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid Contours').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'AllChannels', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid AllChannels').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'Decibel', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid Decibel').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'EvokedOscillations', answer{1,9})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TransformPower', answer{1,10})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineSubtraction', answer{1,11})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineNormalization', answer{1,12})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded ...
                ]);

                success = success && WTTryExec(@()plotsPrms.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 
            end
        end

        function success = defineAvgStdErrPlotsSettings(plotsPrms, lockEvok, lockPower, lockBaselineCorrect, lockBaselineNorm)
            success = false; 
            WTValidations.mustBe(plotsPrms, ?WTAvgStdErrPlotsCfg);
            wtLog = WTLog();

            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');
            enableBC = WTCodingUtils.ifThenElse(lockBaselineCorrect, 'off', 'on');
            enableBN = WTCodingUtils.ifThenElse(lockBaselineNorm, 'off', 'on');

            answer = { ...
                num2str(plotsPrms.TimeMin) ...
                num2str(plotsPrms.TimeMax) ...
                num2str(plotsPrms.FreqMin) ...
                num2str(plotsPrms.FreqMax) ...
                plotsPrms.AllChannels ... 
                plotsPrms.Decibel ...
                plotsPrms.EvokedOscillations ...
                plotsPrms.TransformPower ...
                plotsPrms.BaselineSubtraction ...
                plotsPrms.BaselineNormalization ...
            };
            
            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'     'string' 'Time (ms): From     ' } ...
                    { 'style' 'edit'     'string' answer{1,1} } ...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,2} }...
                    { 'style' 'text'     'string' 'Frequency (Hz): From' } ...
                    { 'style' 'edit'     'string' answer{1,3} }...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,4} }...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Plot all channels' 'value'  answer{1,5} } ...
                    { 'style' 'checkbox' 'string' 'Decibel' 'value'  answer{1,6} } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Evoked Oscillations' 'value'  answer{1,7} 'enable' enableEvok } ...
                    { 'style' 'checkbox' 'string' 'Transform Power' 'value'  answer{1,8} 'enable' enablePower } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Baseline Subtraction' 'value' answer{1,9} 'enable' enableBC } ...
                    { 'style' 'checkbox' 'string' 'Baseline Normalization' 'value' answer{1,10} 'enable' enableBN } ...
                    { 'style' 'text'     'string' '' } ...
                };
            end

            geometry = { [0.25 0.15 0.15 0.15] [0.25 0.15 0.15 0.15] 1 [0.25 0.3 0.15] [0.25 0.3 0.15] [0.25 0.3 0.15] };

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Set plots parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted average + std error plots configuration dialog');
                    return 
                end

                success = all([ ...
                    WTTryExec(@()set(plotsPrms, 'TimeMin', WTNumUtils.str2double(answer{1,1}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMin').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TimeMax', WTNumUtils.str2double(answer{1,2}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMax').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMin', WTNumUtils.str2double(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMin').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMax', WTNumUtils.str2double(answer{1,4}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMax').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'AllChannels', answer{1,5})).logWrn().displayWrn('Review parameter', 'Invalid AllChannels').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'Decibel', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid Decibel').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'EvokedOscillations', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TransformPower', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineSubtraction', answer{1,9})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineNormalization', answer{1,10})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded ...
                ]);

                success = success && WTTryExec(@()plotsPrms.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 
            end
        end

        function success = defineChansAvgPlotsSettings(plotsPrms, lockEvok, lockPower, lockBaselineCorrect, lockBaselineNorm) 
            success = false;
            WTValidations.mustBe(plotsPrms, ?WTChansAvgPlotsCfg);
            wtLog = WTLog();
            
            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');
            enableBC = WTCodingUtils.ifThenElse(lockBaselineCorrect, 'off', 'on');
            enableBN = WTCodingUtils.ifThenElse(lockBaselineNorm, 'off', 'on');

            scaleLabel = WTPlotUtils.getPlotConfigLabel( ...
                plotsPrms.EvokedOscillations, ...
                plotsPrms.TransformPower, ...
                plotsPrms.BaselineSubtraction, ...
                plotsPrms.BaselineNormalization, ... 
                plotsPrms.Decibel);
            
            if isempty(plotsPrms.Scale)
                plotsPrms.Scale = WTPlotUtils.getSuggestedScaleRange( ...
                    plotsPrms.TransformPower, ...
                    plotsPrms.BaselineSubtraction, ...
                    plotsPrms.BaselineNormalization, ... 
                    plotsPrms.Decibel);
            end

            updateScaleCb = [ WTPlotsGUI.setScaleLabelCb WTPlotsGUI.setScaleRangeCb ];

            answer = { ...
                num2str(plotsPrms.TimeMin) ...
                num2str(plotsPrms.TimeMax) ...
                num2str(plotsPrms.FreqMin) ...
                num2str(plotsPrms.FreqMax) ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Scale)) ...
                plotsPrms.Contours ...
                plotsPrms.AllChannels ...
                plotsPrms.Decibel ...
                plotsPrms.EvokedOscillations ...
                plotsPrms.TransformPower ...
                plotsPrms.BaselineSubtraction ...
                plotsPrms.BaselineNormalization ...
            };
            
            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'     'string' 'Time (ms): From     ' } ...
                    { 'style' 'edit'     'string' answer{1,1} } ...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,2} }...
                    { 'style' 'text'     'string' 'Frequency (Hz): From' } ...
                    { 'style' 'edit'     'string' answer{1,3} }...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,4} }...
                    { 'style' 'text'     'string' scaleLabel 'tag' 'LB' } ...
                    { 'style' 'edit'     'string' answer{1,5} 'tag' 'RG' }...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Draw contours' 'value'  answer{1,6} } ...
                    { 'style' 'checkbox' 'string' 'Plot all channels' 'value'  answer{1,7} } ...
                    { 'style' 'checkbox' 'string' 'Decibel' 'value'  answer{1,8} 'tag' 'DB' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Evoked Oscillations' 'value'  answer{1,9} 'enable' enableEvok 'tag' 'EO' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Transform Power' 'value'  answer{1,10} 'enable' enablePower 'tag' 'PW' 'callback' updateScaleCb } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Baseline Subtraction' 'value' answer{1,11} 'enable' enableBC 'tag' 'BC' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Baseline Normalization' 'value' answer{1,12} 'enable' enableBN  'tag' 'BN' 'callback' updateScaleCb } ...
                    { 'style' 'text'     'string' '' } ...
                };
            end

            geometry = { 
                [0.25 0.15 0.15 0.15] ...
                [0.25 0.15 0.15 0.15] ...
                [0.25 0.45] ...
                1 ...
                [0.25 0.25 0.3] ...
                [0.25 0.25 0.3] ...
                [0.25 0.25 0.3] ...
            };

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Set plots parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted channels average plots configuration dialog');
                    return 
                end

                success = all([ ...
                    WTTryExec(@()set(plotsPrms, 'TimeMin', WTNumUtils.str2double(answer{1,1}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMin').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TimeMax', WTNumUtils.str2double(answer{1,2}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMax').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMin', WTNumUtils.str2double(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMin').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMax', WTNumUtils.str2double(answer{1,4}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMax').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Scale', WTNumUtils.str2nums(answer{1,5}))).logWrn().displayWrn('Review parameter', 'Invalid Scale').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Contours', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid Contours').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'AllChannels', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid AllChannels').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Decibel', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid Decibel').run().Succeeded ...  
                    WTTryExec(@()set(plotsPrms, 'EvokedOscillations', answer{1,9})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TransformPower', answer{1,10})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineSubtraction', answer{1,11})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineNormalization', answer{1,12})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded ...
                ]);

                success = success && WTTryExec(@()plotsPrms.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 
            end
        end

        function success = defineChansAvgStdErrPlotsSettings(plotsPrms, lockEvok, lockPower, lockBaselineCorrect, lockBaselineNorm)
            success = false; 
            WTValidations.mustBe(plotsPrms, ?WTChansAvgStdErrPlotsCfg);
            wtLog = WTLog();

            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');
            enableBC = WTCodingUtils.ifThenElse(lockBaselineCorrect, 'off', 'on');
            enableBN = WTCodingUtils.ifThenElse(lockBaselineNorm, 'off', 'on');

            answer = { ...
                num2str(plotsPrms.TimeMin) ...
                num2str(plotsPrms.TimeMax) ...
                num2str(plotsPrms.FreqMin) ...
                num2str(plotsPrms.FreqMax) ...
                plotsPrms.AllChannels ...
                plotsPrms.Decibel ...
                plotsPrms.EvokedOscillations ...
                plotsPrms.TransformPower ...
                plotsPrms.BaselineSubtraction ...
                plotsPrms.BaselineNormalization ...
            };
            
            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'     'string' 'Time (ms): From     ' } ...
                    { 'style' 'edit'     'string' answer{1,1} } ...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,2} }...
                    { 'style' 'text'     'string' 'Frequency (Hz): From' } ...
                    { 'style' 'edit'     'string' answer{1,3} }...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,4} }...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Plot all channels' 'value'  answer{1,5} } ...
                    { 'style' 'checkbox' 'string' 'Decibel' 'value'  answer{1,6} } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Evoked Oscillations' 'value'  answer{1,7} 'enable' enableEvok } ...
                    { 'style' 'checkbox' 'string' 'Transform Power' 'value'  answer{1,8} 'enable' enablePower } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Baseline Subtraction' 'value' answer{1,9} 'enable' enableBC } ...
                    { 'style' 'checkbox' 'string' 'Baseline Normalization' 'value' answer{1,10} 'enable' enableBN } ...
                    { 'style' 'text'     'string' '' } ...
                };
            end

            geometry = { [0.25 0.15 0.15 0.15] [0.25 0.15 0.15 0.15] 1 [0.25 0.25 0.25] [0.25 0.25 0.25] [0.25 0.25 0.25] };

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Set plots parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted channels average + std error plots configuration dialog');
                    return 
                end

                success = all([ ...
                    WTTryExec(@()set(plotsPrms, 'TimeMin', WTNumUtils.str2double(answer{1,1}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMin').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TimeMax', WTNumUtils.str2double(answer{1,2}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMax').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMin', WTNumUtils.str2double(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMin').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'FreqMax', WTNumUtils.str2double(answer{1,4}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMax').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'AllChannels', answer{1,5})).logWrn().displayWrn('Review parameter', 'Invalid AllChannels').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Decibel', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid Decibel').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'EvokedOscillations', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TransformPower', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineSubtraction', answer{1,9})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineNormalization', answer{1,10})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded ...
                ]);

                success = success && WTTryExec(@()plotsPrms.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 
            end
        end

        function success = define2DScalpMapPlotsSettings(plotsPrms, maxSerieLength, lockEvok, lockPower, lockBaselineCorrect, lockBaselineNorm)
            success = false; 
            WTValidations.mustBe(plotsPrms, ?WT2DScalpMapPlotsCfg);
            maxSerieLength = WTCodingUtils.ifThenElse(nargin > 2, @()maxSerieLength, 0);
            wtLog = WTLog();
            
            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');
            enableBC = WTCodingUtils.ifThenElse(lockBaselineCorrect, 'off', 'on');
            enableBN = WTCodingUtils.ifThenElse(lockBaselineNorm, 'off', 'on');

            scaleLabel = WTPlotUtils.getPlotConfigLabel( ...
                plotsPrms.EvokedOscillations, ...
                plotsPrms.TransformPower, ...
                plotsPrms.BaselineSubtraction, ...
                plotsPrms.BaselineNormalization, ... 
                plotsPrms.Decibel);
            
            if isempty(plotsPrms.Scale)
                plotsPrms.Scale = WTPlotUtils.getSuggestedScaleRange( ...
                    plotsPrms.TransformPower, ...
                    plotsPrms.BaselineSubtraction, ...
                    plotsPrms.BaselineNormalization, ... 
                    plotsPrms.Decibel);
            end

            updateScaleCb = [ WTPlotsGUI.setScaleLabelCb WTPlotsGUI.setScaleRangeCb ];

            answer = { ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Time)) ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Frequency)) ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Scale)) ...
                plotsPrms.PeripheralElectrodes ...
                plotsPrms.ElectrodesLabel ...
                plotsPrms.Contours ... 
                plotsPrms.Decibel ...
                plotsPrms.EvokedOscillations ...
                plotsPrms.TransformPower ...
                plotsPrms.BaselineSubtraction ...
                plotsPrms.BaselineNormalization ...
            };
            
            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'     'string' 'Time (ms): From-[pace]-To     ' } ...
                    { 'style' 'edit'     'string'  answer{1,1} } ...
                    { 'style' 'text'     'string' 'Frequency (Hz): From-[pace]-To' } ...
                    { 'style' 'edit'     'string'  answer{1,2} } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'text'     'string' 'NOTE: The pace is optional and defines time / frequency series. The pace can be defined either' } ...
                    { 'style' 'text'     'string' '             for time or frequency, not both. Small paces can slow down sensibly the processing.' } ...
                    { 'style' 'text'     'string' '             Example: Frequency = [1 10 201] => 20 frequency based subplots.' } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'text'     'string'  scaleLabel 'tag' 'LB' } ...
                    { 'style' 'edit'     'string'  answer{1,3} 'tag' 'RG' } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Peripheral Electrodes' 'value'  answer{1,4} } ...
                    { 'style' 'checkbox' 'string' 'Electrode labels' 'value' answer{1,5} } ...
                    { 'style' 'checkbox' 'string' 'Draw contours' 'value' answer{1,6} } ....
                    { 'style' 'checkbox' 'string' 'Decibel' 'value' answer{1,7} 'tag' 'DB' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Evoked Oscillations' 'value'  answer{1,8} 'enable' enableEvok 'tag' 'EO' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Transform Power' 'value'  answer{1,9} 'enable' enablePower 'tag' 'PW' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox' 'string' 'Baseline Subtraction' 'value' answer{1,10} 'enable' enableBC 'tag' 'BC' 'callback' updateScaleCb  } ...
                    { 'style' 'checkbox' 'string' 'Baseline Normalization' 'value' answer{1,11} 'enable' enableBN 'tag' 'BN' 'callback' updateScaleCb } ...
                };
            end
            
            geometry = { [1 1] [1 1] 1 1 1 1 1 [1 1] 1 [1 1] [1 1] [1 1] [1 1] };

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Set plots parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted 2D scalp map plots configuration dialog');
                    return 
                end

                success = all([ ...
                    WTTryExec(@()set(plotsPrms, 'Time', answer{1,1})).logWrn().displayWrn('Review parameter', 'Invalid Time').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Frequency', answer{1,2})).logWrn().displayWrn('Review parameter', 'Invalid Frequency').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'Scale', WTNumUtils.str2nums(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid Scale').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'PeripheralElectrodes', answer{1,4})).logWrn().displayWrn('Review parameter', 'Invalid PeripheralElectrodes').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'ElectrodesLabel', answer{1,5})).logWrn().displayWrn('Review parameter', 'Invalid ElectrodesLabel').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Contours', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid Contours').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Decibel', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid Decibel').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'EvokedOscillations', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TransformPower', answer{1,9})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineSubtraction', answer{1,10})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineNormalization', answer{1,11})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded ...
                ]);
                
                success = success && WTTryExec(@()plotsPrms.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 

                if maxSerieLength > 0 && ~isempty(plotsPrms.TimeResolution) 
                    n = length(plotsPrms.TimeMin : plotsPrms.TimeResolution : plotsPrms.TimeMax);
                    if maxSerieLength < n 
                        WTDialogUtils.wrnDlg('Review parameter', ...
                            [ 'You defined a time serie with %d samples which reflects into as many plots.' ... 
                              'The application manages max %d plots. Adjust please.' ], ...
                              n, maxSerieLength)
                        success = false;
                        continue
                    end
                end
                
                if maxSerieLength > 0 && ~isempty(plotsPrms.FreqResolution) 
                    n = length(plotsPrms.FreqMin : plotsPrms.FreqResolution : plotsPrms.FreqMax);
                    if maxSerieLength < n
                        WTDialogUtils.wrnDlg('Review parameter', ...
                            [ 'You defined a frequency serie with %d samples which reflects into as many plots.' ... 
                              'The application manages max %d plots. Adjust please.' ], ...
                               n, maxSerieLength)
                        success = false;
                        continue
                    end
                end

            end
            success = true;
        end

        function success = define3DScalpMapPlotsSettings(plotsPrms, lockEvok, lockPower, lockBaselineCorrect, lockBaselineNorm)
            success = false; 
            WTValidations.mustBe(plotsPrms, ?WT3DScalpMapPlotsCfg);
            ioProc = WTProject().Config.IOProc;
            wtLog = WTLog();
            
            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');
            enableBC = WTCodingUtils.ifThenElse(lockBaselineCorrect, 'off', 'on');
            enableBN = WTCodingUtils.ifThenElse(lockBaselineNorm, 'off', 'on');

            scaleLabel = WTPlotUtils.getPlotConfigLabel( ...
                plotsPrms.EvokedOscillations, ...
                plotsPrms.TransformPower, ...
                plotsPrms.BaselineSubtraction, ...
                plotsPrms.BaselineNormalization, ... 
                plotsPrms.Decibel);
            
            if isempty(plotsPrms.Scale)
                plotsPrms.Scale = WTPlotUtils.getSuggestedScaleRange( ...
                    plotsPrms.TransformPower, ...
                    plotsPrms.BaselineSubtraction, ...
                    plotsPrms.BaselineNormalization, ... 
                    plotsPrms.Decibel);
            end

            updateScaleCb = [ WTPlotsGUI.setScaleLabelCb WTPlotsGUI.setScaleRangeCb ];

            answer = { ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Time)) ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Frequency)) ...
                sprintf(WTConfigFormatter.FmtArray, num2str(plotsPrms.Scale)) ...
                plotsPrms.SplineFile, ...
                plotsPrms.Decibel ...
                plotsPrms.EvokedOscillations ...
                plotsPrms.TransformPower ...
                plotsPrms.BaselineSubtraction ...
                plotsPrms.BaselineNormalization ...
            };
            
            function splineFile = selectSplineFile()
                [splineFile, ~, ~] = WTDialogUtils.uiGetFiles(ioProc.SplineFileTypeFlt, -1, -1, 'Select spline file', ...
                    'MultiSelect', 'off', 'restrictToDirs', ['^' regexptranslate('escape', WTLayout.getSplinesDir()) ], ...
                    WTLayout.getSplinesDir());
            end

            userData = struct();
            userData.selectSplineFile = @selectSplineFile;
            
            cbSetSpline = [
                'h = findobj(gcbf, ''tag'', ''spline'');' ...
                'v = get(h, ''userdata'').selectSplineFile();' ...
                'if ~isempty(v)' ...
                '   set(h, ''string'', v);' ...
                'end' ...
            ];

            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'       'string' 'Time (ms): From - To     ' } ...
                    { 'style' 'edit'       'string'  answer{1,1} } ...
                    { 'style' 'text'       'string' 'Frequency (Hz): From - To' } ...
                    { 'style' 'edit'       'string'  answer{1,2} } ...
                    { 'style' 'text'       'string'  scaleLabel 'tag' 'LB'} ...
                    { 'style' 'edit'       'string'  answer{1,3} 'tag' 'RG' } ...
                    { 'style' 'text'       'string' '' } ...
                    { 'style' 'text'       'string' 'Spline reference' } ...
                    { 'style' 'pushbutton' 'string' 'Set' 'callback' cbSetSpline } ...
                    { 'style' 'edit'       'string'  answer{1,4} 'tag' 'spline' 'enable' 'off' 'userdata' userData } ...
                    { 'style' 'text'       'string' '' } ...
                    { 'style' 'checkbox'   'string' 'Decibel' 'value' answer{1,5} 'tag' 'DB' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox'   'string' 'Evoked Oscillations' 'value'  answer{1,6} 'enable' enableEvok 'tag' 'EO' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox'   'string' 'Transform Power' 'value'  answer{1,7} 'enable' enablePower 'tag' 'PW' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox'   'string' 'Baseline Subtraction' 'value' answer{1,8} 'enable' enableBC 'tag' 'BC' 'callback' updateScaleCb } ...
                    { 'style' 'checkbox'   'string' 'Baseline Normalization' 'value' answer{1,9} 'enable' enableBN 'tag' 'BN' 'callback' updateScaleCb } ...
                };
            end
            
            geometry = { [1 1] [1 1] [1 1] 1 1 [0.15 0.85] 1 1 [1 1] [1 1] };

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'uilist', parameters, 'title', 'Set plots parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted 3D scalp map plots configuration dialog');
                    return 
                end

                success = all([ ...
                    WTTryExec(@()set(plotsPrms, 'Time', answer{1,1})).logWrn().displayWrn('Review parameter', 'Invalid Time').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Frequency', answer{1,2})).logWrn().displayWrn('Review parameter', 'Invalid Frequency').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'Scale', WTNumUtils.str2nums(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid Scale').run().Succeeded ... 
                    WTTryExec(@()set(plotsPrms, 'SplineFile', answer{1,4})).logWrn().displayWrn('Review parameter', 'Invalid SplineFile').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'Decibel', answer{1,5})).logWrn().displayWrn('Review parameter', 'Invalid Decibel').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'EvokedOscillations', answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'TransformPower', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineSubtraction', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ...
                    WTTryExec(@()set(plotsPrms, 'BaselineNormalization', answer{1,9})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded ...
                ]);

                success = success && WTTryExec(@()plotsPrms.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 
            end
        end
    end
end