% Copyright (C) 2024 Eugenio Parise, Luca Filippin
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <https://www.gnu.org/licenses/>.

classdef WTStatisticsGUI

    methods(Static)

        function [success, subjectsList, conditionsList] = defineStatisticsSettings(statsPrms, ...
            subjectsList, conditionsList, lockEvok, lockPower, lockBaselineCorrect, lockBaselineNorm)

            success = false;
            WTValidations.mustBe(statsPrms, ?WTStatisticsCfg);
            WTValidations.mustBeLinearCellArrayOfChar(subjectsList);
            WTValidations.mustBeLinearCellArrayOfChar(conditionsList);
            wtLog = WTLog();

            if isempty(subjectsList)
                WTDialogUtils.errDlg('Bad parameter', 'There project subjects list is empty!');
                return
            end

            if isempty(conditionsList)
                WTDialogUtils.errDlg('Bad parameter', 'The project conditions list is empty!');
                return
            end

            subjects = subjectsList;
            conditions = conditionsList;
            enableEvok = WTCodingUtils.ifThenElse(lockEvok, 'off', 'on');
            enablePower = WTCodingUtils.ifThenElse(lockPower, 'off', 'on');
            enableBC = WTCodingUtils.ifThenElse(lockBaselineCorrect, 'off', 'on');
            enableBN = WTCodingUtils.ifThenElse(lockBaselineNorm, 'off', 'on');

            answer = { ...
                num2str(statsPrms.TimeMin) ...
                num2str(statsPrms.TimeMax) ...
                num2str(statsPrms.FreqMin) ...
                num2str(statsPrms.FreqMax) ...
                [], ...
                [], ... 
                statsPrms.IndividualFreqs ...
                statsPrms.EvokedOscillations ...
                statsPrms.TransformPower ...
                statsPrms.BaselineSubtraction ...
                statsPrms.BaselineNormalization ...
            };

            function params = setParameters(answer) 
                params = { ...
                    { 'style' 'text'     'string' 'Time (ms): From     ' } ...
                    { 'style' 'edit'     'string' answer{1,1} } ...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,2} }...
                    { 'style' 'text'     'string' 'Frequency (Hz): From' } ...
                    { 'style' 'edit'     'string' answer{1,3} }...
                    { 'style' 'text'     'string' 'To' } ...
                    { 'style' 'edit'     'string' answer{1,4} }.....
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'text'     'string' 'Subjects (no selection = all)'   } ...
                    { 'style' 'text'     'string' 'Conditions (no selection = all)' } ...
                    { 'style' 'listbox'  'tag'  'subjs' 'string' subjects   'value' answer{1,5} 'min' 0 'max' length(subjects) }, ...
                    { 'style' 'listbox'  'tag'  'conds' 'string' conditions 'value' answer{1,6} 'min' 0 'max' length(conditions) }, ...
                    { 'style' 'checkbox' 'string' 'Retrieve individual frequencies' 'value'  answer{1,7} } ...
                    { 'style' 'text'     'string' '' } ...
                    { 'style' 'checkbox' 'string' 'Evoked Oscillations' 'value'  answer{1,8} 'enable' enableEvok } ...
                    { 'style' 'checkbox' 'string' 'Transform Power' 'value'  answer{1,9} 'enable' enablePower } ...
                    { 'style' 'checkbox' 'string' 'Baseline Subtraction' 'value'  answer{1,10} 'enable' enableBC } ...
                    { 'style' 'checkbox' 'string' 'Baseline Normalization' 'value'  answer{1,11} 'enable' enableBN } ...s
                };
            end

            geometry = { [0.25 0.15 0.15 0.15] [0.25 0.15 0.15 0.15] 1 [0.5 0.5] [0.5 0.5] 1 1 [0.5 0.5] [0.5 0.5] };
            geomvert = [ 1 1 1 1 min(max(length(subjects), length(conditions)), 10) 1 1 1 1 ];

            while ~success
                parameters = setParameters(answer);
                answer = WTEEGLabUtils.eeglabInputMask('geometry', geometry, 'geomvert', geomvert, 'uilist', parameters, 'title', 'Set statistics parameters');
                
                if isempty(answer)
                    wtLog.dbg('User quitted statistics configuration dialog');
                    return 
                end

                success = all([ ...
                    WTTryExec(@()set(statsPrms, 'TimeMin', WTNumUtils.str2double(answer{1,1}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMin').run().Succeeded ...
                    WTTryExec(@()set(statsPrms, 'TimeMax', WTNumUtils.str2double(answer{1,2}))).logWrn().displayWrn('Review parameter', 'Invalid TimeMax').run().Succeeded ... 
                    WTTryExec(@()set(statsPrms, 'FreqMin', WTNumUtils.str2double(answer{1,3}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMin').run().Succeeded ... 
                    WTTryExec(@()set(statsPrms, 'FreqMax', WTNumUtils.str2double(answer{1,4}))).logWrn().displayWrn('Review parameter', 'Invalid FreqMax').run().Succeeded ...
                    WTTryExec(@()subjects(answer{1,5})).logWrn().displayWrn('Review parameter', 'Invalid Subjects selection').run().Succeeded ... 
                    WTTryExec(@()conditions(answer{1,6})).logWrn().displayWrn('Review parameter', 'Invalid Conditions selection').run().Succeeded ... 
                    WTTryExec(@()set(statsPrms, 'IndividualFreqs', answer{1,7})).logWrn().displayWrn('Review parameter', 'Invalid IndividualFreqs').run().Succeeded ... 
                    WTTryExec(@()set(statsPrms, 'EvokedOscillations', answer{1,8})).logWrn().displayWrn('Review parameter', 'Invalid EvokedOscillations').run().Succeeded ... 
                    WTTryExec(@()set(statsPrms, 'TransformPower', answer{1,9})).logWrn().displayWrn('Review parameter', 'Invalid TransformPower').run().Succeeded ...
                    WTTryExec(@()set(statsPrms, 'BaselineSubtraction', answer{1,10})).logWrn().displayWrn('Review parameter', 'Invalid BaselineSubtraction').run().Succeeded ...
                    WTTryExec(@()set(statsPrms, 'BaselineNormalization', answer{1,11})).logWrn().displayWrn('Review parameter', 'Invalid BaselineNormalization').run().Succeeded
                ]);

                success = success && WTTryExec(@()statsPrms.validate(true)).logWrn().displayWrn('Review parameter', 'Validation failure').run().Succeeded; 

                if success
                    subjectsList = subjects(answer{1,5});
                    conditionsList = conditions(answer{1,6});
                end
            end
        end

    end
end