
classdef WTDifferenceGUI
    
    methods(Static)
        function success = defineDifferenceParams(differencePrms, conditionsGrandPrms, logFlag, evokFlag)
            success = false;
            wtLog = WTLog();

            WTValidations.mustBeA(differencePrms, ?WTDifferenceCfg)
            WTValidations.mustBeA(conditionsGrandPrms, ?WTConditionsGrandCfg)

            if differencePrms.exist()
                answer = { differencePrms.Condition1,  differencePrms.Condition2, differencePrms.ConditionDiff, ...
                    differencePrms.LogDiff, differencePrms.EvokedOscillations };
            else
                answer = { 1, 1, 1, 0, evokFlag }; 
            end 
            
            % Assign conditions and condiff to the base workspace to prevent errors of the gui
            conditions = conditionsGrandPrms.ConditionsList;
            condiff = conditionsGrandPrms.ConditionsDiff;
            ws = WTWorkspace();
            ws.pushBase();

            try
                assignin('base','conditions', conditions);
                assignin('base','condiff', condiff);
                
                cbList1 = [ ...
                    'tmpdat = get(gcbf, ''userdata'');' ...
                    'tmpval1 = get(findobj(gcbf, ''tag'', ''list1''), ''value'');' ...
                    'tmppos1 = conditions(tmpval1);' ];
                
                cbList2 = [ ...
                    'tmpdat = get(gcbf, ''userdata'');' ...
                    'tmpval2 = get(findobj(gcbf, ''tag'', ''list2''), ''value'');' ...
                    'tmppos2 = conditions(tmpval2);' ];
                
                cbList3 = [ ...
                    'tmpdat = get(gcbf, ''userdata'');' ...
                    'tmpval3 = get(findobj(gcbf, ''tag'', ''list3''), ''value'');' ...
                    'tmppos3 = condiff(tmpval3);' ];
                
                cbPair = [ ...
                    'if ~exist(''tmppos1'',''var''),' ...
                    '  tmppos1 = [];' ...
                    'end;' ...
                    'if ~exist(''tmppos2'',''var''),' ...
                    '  tmppos2 = [];' ...
                    'end;' ...
                    'if isempty(tmppos1) && isempty(tmppos2),' ...
                    '  if sum(ismember(condiff,strcat(conditions{1},''-'',conditions{1})))>0' ...
                    '    WTLog().warn(''Difference already set!'');' ...
                    '  else;' ...
                    '    condiff=cat(2,condiff,strcat(conditions{1},''-'',conditions{1}));' ...
                    '    set(findobj(gcbf, ''tag'', ''list3''), ''string'', condiff);' ...
                    '  end;' ...
                    'elseif ~isempty(tmppos1) && isempty(tmppos2),' ...
                    '  if sum(ismember(condiff,strcat(tmppos1{1},''-'',conditions{1})))>0' ...
                    '    WTLog().warn(''Difference already set!'');' ...
                    '  else;' ...
                    '    condiff=cat(2,condiff,strcat(tmppos1{1},''-'',conditions{1}));' ...
                    '    set(findobj(gcbf, ''tag'', ''list3''), ''string'', condiff);' ...
                    '  end;' ...
                    'elseif isempty(tmppos1) && ~isempty(tmppos2),' ...
                    '  if sum(ismember(condiff,strcat(conditions{1},''-'',tmppos2{1})))>0' ...
                    '    WTLog().warn(''Difference already set!'');' ...
                    '  else;' ...
                    '    condiff=cat(2,condiff,strcat(conditions{1},''-'',tmppos2{1}));' ...
                    '    set(findobj(gcbf, ''tag'', ''list3''), ''string'', condiff);' ...
                    '  end;' ...
                    'elseif ~isempty(tmppos1) && ~isempty(tmppos2),' ...
                    '  if sum(ismember(condiff,strcat(tmppos1{1},''-'',tmppos2{1})))>0' ...
                    '    WTLog().warn(''Difference already set!'');' ...
                    '  else;' ...
                    '    condiff=cat(2,condiff,strcat(tmppos1{1},''-'',tmppos2{1}));' ...
                    '    set(findobj(gcbf, ''tag'', ''list3''), ''string'', condiff);' ...
                    '  end;' ...
                    'end;' ];
                
                cbDel = [ ...
                    'if isempty(condiff),' ...
                    '  WTLog().warn(''No difference to delete!'');' ...
                    'else;' ...
                    '  tmpdat = get(gcbf, ''userdata'');' ...
                    '  tmpval3 = get(findobj(gcbf, ''tag'', ''list3''), ''value'');' ...
                    '  condiff(tmpval3)=[];' ...
                    '  set(findobj(gcbf, ''tag'', ''list3''), ''Value'', 1);' ...
                    '  set(findobj(gcbf, ''tag'', ''list3''), ''string'', condiff);' ...
                    'end;' ];
                
                geometry = { [4 4 2 4] [4 4 2 4] };
                geomvert = [ min(max(length(conditions)), 10) 1 ];
                
                parameters = { ...
                    { 'Style'   'listbox'    'tag'      'list1'             'string'        conditions  'value' answer{1,1} 'callback' cbList1 }, ...
                    { 'Style'   'listbox'    'tag'      'list2'             'string'        conditions  'value' answer{1,2} 'callback' cbList2 }, ...
                    { 'Style'   'pushbutton' 'string'   '=>'                'callback'      cbPair } ...
                    { 'Style'   'listbox'    'tag'      'list3'             'string'        condiff     'value' answer{1,3} 'callback' cbList3 } ...
                    { 'style'   'checkbox'   'string'   'Log10-Transformed data'            'value'   logFlag 'enable' 'off' } ...
                    { 'style'   'checkbox'   'string'   'Evoked Oscillations'               'value'   answer{1,5} } ...
                    { 'style'   'text'       'string'   '' } ...
                    { 'Style'   'pushbutton' 'string'   'Delete difference' 'callback'      cbDel } };
                
                [answer, ~, strhalt] = WTUtils.eeglabInputMask('geometry', geometry, 'geomvert', geomvert, 'uilist', parameters, 'title', 'Define differences to compute');
                condiff = evalin('base','condiff');

                if strcmp(strhalt,'retuninginputui') && ~isempty(answer) && ~isempty(condiff)
                    conditionsGrandPrms.ConditionsDiff = condiff;
                    differencePrms.Condition1 = answer{1,1};
                    differencePrms.Condition2 = answer{1,2};
                    differencePrms.ConditionDiff = answer{1,3};
                    differencePrms.LogDiff = answer{1,4};
                    differencePrms.EvokedOscillations = answer{1,5};
                    success = true;
                end

            catch me
                wtLog.except(me)
                return
            end

            ws.popToBase(true);
        end
    end
end